### ISSUE TITLE
green-recorder missing ImageMagick-tools on fedora 32

### ISSUE THREAD

**Issue by Akiyamka** [rpmsphere/x86_64#8]

**Comment by bluebat** [comment]
fixed and updated.

**Comment by Akiyamka** [comment]
@bluebat thank you. But app still not run
```
green-recorder
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 17, in <module>
    import gi
ImportError: No module named gi
```
 Can you also add `python2-gobject` and `python2-pydbus` ?

From [tread](https://www.linuxquestions.org/questions/linux-software-2/green-recorder-syntaxerror-invalid-syntax-when-executing-the-binary-python-2-7-fedora-32-a-4175675498/):
> The package python2-gobject was dropped from Fedora 32. From the changelog:
 ```
2020-01-16 - Miro Hrončok <mhroncok@redhat.com> - 3.34.0-4
Subpackages python2-gobject, python2-gobject-base, python2-gobject-devel have been removed
See https://fedoraproject.org/wiki/Changes/RetirePython2
```

**Comment by bluebat** [comment]
upgraded to python3 version from https://github.com/damianmoore/

**Comment by Akiyamka** [comment]
awesome now it work!
